// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200602222727");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.normandy.user_id", "03f22217-409c-450b-9f01-99da212717af");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1591666637);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1591666877);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1591665217);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1591666488);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1591252416);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1591666517);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1591252326);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1591666757);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 29338);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1591247965);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1bb82116-3960-4fb3-a6e2-208664bcf643}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1591668841036");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1591670659036");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1591668817545");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1591672417545");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200602222727");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1591666488");
user_pref("browser.slowStartup.averageTime", 2673);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20200602222727");
user_pref("browser.startup.homepage_override.mstone", "77.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1591666487);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1591247970474");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "77.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "90a17cd6f4344bb5a95465ac4c760115");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1591666638);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200602222727");
user_pref("extensions.lastAppVersion", "77.0.1");
user_pref("extensions.lastPlatformVersion", "77.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"bee95a5f-2e6f-4632-b0b8-2b49d286831e\",\"formautofill@mozilla.org\":\"f444d969-5b75-48f4-a47f-39a010513388\",\"screenshots@mozilla.org\":\"9e8e75a1-85d9-4801-bed3-ba98aea9a6e3\",\"webcompat-reporter@mozilla.org\":\"147f8c70-9b01-46e9-b864-e5a3933a3bf9\",\"webcompat@mozilla.org\":\"79b2a7d1-3af7-41cd-bb2d-1e94bd1d8788\",\"default-theme@mozilla.org\":\"529e7f54-9541-4e7c-965d-b2853edfcc02\",\"google@search.mozilla.org\":\"141955e6-621c-4ec7-92f4-11ad11a7c1dd\",\"amazondotcom@search.mozilla.org\":\"85c825ce-b9ac-49d2-b50b-dff3155cd876\",\"bing@search.mozilla.org\":\"e43868d7-0792-4019-b99e-370bd8a4b42a\",\"ddg@search.mozilla.org\":\"7bc08aa0-e1df-4fb8-9961-5e724393f7d0\",\"ebay@search.mozilla.org\":\"13f5cee5-2db5-459c-97ba-8ac31a5ff899\",\"twitter@search.mozilla.org\":\"0cd0e601-b1c1-4d24-b967-878992e8e108\",\"wikipedia@search.mozilla.org\":\"30221b6e-f6ca-45d9-9cc3-0d839fdc8df5\",\"naver-kr@search.mozilla.org\":\"81306446-78e7-45b8-a4ad-f69b9332e5ca\",\"daum-kr@search.mozilla.org\":\"1a090896-a0cb-4ae6-86fb-096807211ca9\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1591252385);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200602222727");
user_pref("media.gmp-manager.lastCheck", 1591666992);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "259dc907-0fda-4c3c-bef4-6738a6b2a898");
user_pref("security.sandbox.plugin.tempDirSuffix", "1f0e4174-2d83-40e0-8928-cbad30252416");
user_pref("services.blocklist.addons.checked", 1591666572);
user_pref("services.blocklist.gfx.checked", 1591666572);
user_pref("services.blocklist.plugins.checked", 1591666572);
user_pref("services.settings.clock_skew_seconds", -56);
user_pref("services.settings.last_etag", "\"1591649665585\"");
user_pref("services.settings.last_update_seconds", 1591666572);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1591666572);
user_pref("services.settings.main.cfr-fxa.last_check", 1591666572);
user_pref("services.settings.main.cfr.last_check", 1591666572);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1591666572);
user_pref("services.settings.main.hijack-blocklists.last_check", 1591666572);
user_pref("services.settings.main.language-dictionaries.last_check", 1591666572);
user_pref("services.settings.main.messaging-experiments.last_check", 1591666572);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1591666572);
user_pref("services.settings.main.search-config.last_check", 1591666572);
user_pref("services.settings.main.sites-classification.last_check", 1591666572);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1591666572);
user_pref("services.settings.main.whats-new-panel.last_check", 1591666572);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1591666486);
user_pref("toolkit.telemetry.cachedClientID", "fd58e462-e294-4a14-a6e0-d925d5e3b7a4");
user_pref("toolkit.telemetry.previousBuildID", "20200602222727");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
